Total Throughput = SUM(operations_kpis[throughput_units])

Total Throughput Target = SUM(operations_kpis[throughput_target])

Throughput Attainment % = DIVIDE([Total Throughput], [Total Throughput Target], 0)

Average Quality % = AVERAGE(operations_kpis[quality_pct])

Average On-Time % = AVERAGE(operations_kpis[on_time_pct])

Backlog Items = SUM(operations_kpis[backlog_items])

Incident Count = COUNTROWS(incident_log)
